<a href="https://colab.research.google.com/github/sanjana1391/Sanjana-DAML-2021-22/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv("/content/Org_profit.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        1000 non-null   float64
 1   Administration   1000 non-null   float64
 2   Marketing Spend  1000 non-null   float64
 3   State            1000 non-null   object 
 4   Profit           1000 non-null   float64
dtypes: float64(4), object(1)
memory usage: 39.2+ KB


In [5]:
x=df.iloc[:,:-2].values
y=df.iloc[:,-1].values
print(x)

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 ...
 [100275.47 241926.31 227142.82]
 [128456.23 321652.14 281692.32]
 [161181.72 270939.86 295442.17]]


In [6]:
x=df[["R&D Spend",	"Administration",	"Marketing Spend"]]
y=df.iloc[:,-1].values
print(x)

     R&D Spend  Administration  Marketing Spend
0    165349.20      136897.800      471784.1000
1    162597.70      151377.590      443898.5300
2    153441.51      101145.550      407934.5400
3    144372.41      118671.850      383199.6200
4    142107.34       91391.770      366168.4200
..         ...             ...              ...
995   54135.00      118451.999      173232.6695
996  134970.00      130390.080      329204.0228
997  100275.47      241926.310      227142.8200
998  128456.23      321652.140      281692.3200
999  161181.72      270939.860      295442.1700

[1000 rows x 3 columns]
