<a href="https://colab.research.google.com/github/sanjana1391/Sanjana-DAML-2021-22/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

In [ ]:
import numpy as np

In [ ]:
myarray=np.array("damon")

In [ ]:
myarray

array('damon', dtype='<U5')

In [ ]:
np.__version__

'1.19.5'

In [ ]:
x=np.array(300)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x

array(300)

In [ ]:
oned=np.array([12,334,56,78,90])
oned

array([ 12, 334,  56,  78,  90])

In [ ]:
type(oned)

numpy.ndarray

In [ ]:
oned.ndim

1

In [ ]:
oned.size

5

In [ ]:
oned.shape

(5,)

2 dimensional array

In [ ]:
twod=np.array([[1,2,3],[23,45,56],[1,4,5]])
twod

array([[ 1,  2,  3],
       [23, 45, 56],
       [ 1,  4,  5]])

In [ ]:
twod.ndim

2

In [ ]:
twod.size

9

In [ ]:
twod.shape

(3, 3)

crreating nd arrays with zeros

In [ ]:
zero=np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x=np.zeros(10, dtype=np.int8)

In [ ]:
#create an array of 2*3 having zero

x=np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
t=np.ones((2,3,3))
t

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

##attributes

1.ndim
2.size
3.shape


In [ ]:
import sys
l=[1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(1)*len(l))
arr=np.array(1)
print(arr.size*arr.itemsize)

252
8


Random

In [ ]:
np.random.rand()

0.8530103203887738

In [ ]:
x=np.random.randint(12)
x

0

In [ ]:
x=np.random.randint(3,11, size=10)
x

array([7, 6, 6, 7, 3, 9, 5, 4, 4, 4])

In [ ]:
x=np.random.rand(3,4)
x

array([[0.68680531, 0.50027514, 0.48676047, 0.70657243],
       [0.05918898, 0.99392527, 0.4051413 , 0.82482689],
       [0.27725428, 0.10646308, 0.92043682, 0.3667004 ]])

In [ ]:
x=np.random.randint(5,10, size=(3,3))
x

array([[8, 8, 6],
       [5, 6, 8],
       [5, 7, 5]])

# choice() method

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
x=np.random.choice(l)
x

5

In [ ]:
l=["vampires","werewolves","angels","demons","griffins"]
x=np.random.choice(l)
x

'angels'

In [ ]:
x=np.random.choice(l,size=(4,3))
x

array([['werewolves', 'vampires', 'griffins'],
       ['vampires', 'werewolves', 'angels'],
       ['vampires', 'demons', 'griffins'],
       ['angels', 'vampires', 'griffins']], dtype='<U10')

acessing elements from array

In [ ]:
x=np.array([12,2,3,45,6,7,8])
x[1]

2

In [ ]:
x=np.array([[12,2,3],[2,6,8],[4,6,7]])
x[1,2]

8

In [ ]:
x=np.array([12,2,3,45,6,7,8])
x[1:3]

array([2, 3])

In [ ]:
#slicing in row major order

x=np.array([[12,2,3],[2,6,8],[4,6,7],[4,3,7]])
x[1:3]

array([[2, 6, 8],
       [4, 6, 7]])

In [ ]:
x[-1:]

array([[4, 3, 7]])

In [ ]:
x[-1:2]

array([], shape=(0, 3), dtype=int64)

In [ ]:
x[:]

array([[12,  2,  3],
       [ 2,  6,  8],
       [ 4,  6,  7],
       [ 4,  3,  7]])

In [ ]:
#slicing in both row and columns

x[0:2,1:2]

array([[2],
       [6]])

In [ ]:
x=np.array([1,5,10,23,45])
x%5==0


array([False,  True,  True, False,  True])

In [ ]:
x=np.array([[12,2,3],[2,6,8],[4,6,7],[4,3,7]])
x[x%2==0]

array([12,  2,  2,  6,  8,  4,  6,  4])

Fancy Indexing

In [ ]:
x=np.random.randint(100,size=(10,6))
x

array([[43, 91, 38, 65, 42,  6],
       [96,  4, 65, 33,  2,  2],
       [70, 24, 66, 28, 64, 33],
       [96, 32, 23, 86, 47,  3],
       [42, 86, 80, 39, 72,  5],
       [ 7, 41, 47, 86, 40, 76],
       [33, 21, 20, 18, 13, 65],
       [77, 39, 62, 55,  9, 49],
       [91,  2, 86,  6, 28,  8],
       [17, 89, 63, 68, 54, 27]])

In [ ]:
x[ :,[2,4,5]]

array([[38, 42,  6],
       [65,  2,  2],
       [66, 64, 33],
       [23, 47,  3],
       [80, 72,  5],
       [47, 40, 76],
       [20, 13, 65],
       [62,  9, 49],
       [86, 28,  8],
       [63, 54, 27]])

In [ ]:
x[[1,3],:]

array([[96,  4, 65, 33,  2,  2],
       [96, 32, 23, 86, 47,  3]])

In [ ]:
x[2:6,[3]]

array([[28],
       [86],
       [39],
       [86]])

In [ ]:
x[2:5][:,3:]

array([[28, 64, 33],
       [86, 47,  3],
       [39, 72,  5]])

Reshaping of arrays

In [ ]:
x=np.arange(1,10)
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x=np.arange(1,10)
x.reshape(3,3).base

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

m=np.array([[1,2],[2,3],[3,4]])
m

array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
np.rot90(m,2)

array([[4, 3],
       [3, 2],
       [2, 1]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.concatenate([x,y],axis=0)
#column should be equal

array([[1, 2, 3],
       [3, 4, 5],
       [3, 5, 7],
       [2, 2, 2],
       [3, 3, 3],
       [5, 5, 5]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.concatenate([x,y],axis=1)
#row should be equal

array([[1, 2, 3, 2, 2, 2],
       [3, 4, 5, 3, 3, 3],
       [3, 5, 7, 5, 5, 5]])

In [ ]:

x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.vstack([x,y])

array([[1, 2, 3],
       [3, 4, 5],
       [3, 5, 7],
       [2, 2, 2],
       [3, 3, 3],
       [5, 5, 5]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.hstack([x,y])

array([[1, 2, 3, 2, 2, 2],
       [3, 4, 5, 3, 3, 3],
       [3, 5, 7, 5, 5, 5]])

In [ ]:
x= np.arange(1,10)
np.split(x,3) #single value passed so in equal parts will be divided
#division should be equal

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
x= np.arange(1,10)
np.split(x,[3,5,6])
#split [0:3],[3:5],[5:6],[6:]

[array([1, 2, 3]), array([4, 5]), array([6]), array([7, 8, 9])]

In [ ]:

x= np.arange(1,10).reshape([3,3])
np.hsplit(x,3)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]

In [ ]:
x= np.arange(1,11).reshape([2,5])
print(x)
np.hsplit(x,[2,5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1, 2],
        [6, 7]]), array([[ 3,  4,  5],
        [ 8,  9, 10]]), array([], shape=(2, 0), dtype=int64)]

In [ ]:
x= np.arange(1,11).reshape([5,2])
print(x)
np.vsplit(x,[3]) #here value is passed in square bracket so splitting will be from [0:3],[3:]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10]])]

In [ ]:

x=np.array([1,2,3,4])
x.dtype

dtype('int64')

In [ ]:
x=np.array([99999999999999999999999,1,2,3,4])
x.dtype

dtype('O')

In [ ]:
x=np.array([1,2,3,4])
y=x.astype(np.float64)
y

array([1., 2., 3., 4.])

ABSOLUTE VALUE

In [ ]:
x=np.array([-1,-2,0,1,2])
np.absolute(x)

array([1, 2, 0, 1, 2])

EXPONENTS AND LOGARITHMS

In [ ]:
#x=e^x
x=[1,2,3]
np.exp(x)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
y=[1,2,3]
np.exp2(y)

array([2., 4., 8.])

In [ ]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

aggregations

In [ ]:
x=np.arange(1,11)
np.add.reduce(x)

55

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

functions


1.   np.sum
2.   np.prod
3.   np.cumsum
4.   np.cumprod



functions

In [ ]:
def myufunc(x):
  return x**3

In [ ]:
x=np.arange(1,11)
cube=np.frompyfunc(myufunc,1,1)
cube(x)

array([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000], dtype=object)

In [ ]:
type(cube)

numpy.ufunc

In [ ]:
type(myufunc)

function

write a universal function which return true if no.is even otherwise false

In [ ]:
def number(n):

   if(n%2==0):
    return True
   else:
    return False


n=int(input())
number(n)


10


True

In [ ]:
glo_num=np.frompyfunc(number,1,1)
number(n)

True

function with 2 arguments

In [ ]:
def abc(x,y):
  return x*y

In [ ]:
glo=np.frompyfunc(abc,2,1)
abc(4,2)

8

*searching arrays*

In [ ]:
x=np.random.randint(1,10,size=10)

np.where(x==4)

(array([8]),)

In [ ]:
np.where(x==4)

(array([8]),)

sort

In [ ]:
data=np.random.randint(10,100,(10,4))
data

array([[35, 74, 31, 50],
       [89, 42, 50, 70],
       [78, 49, 48, 17],
       [16, 78, 45, 69],
       [46, 79, 96, 58],
       [41, 69, 23, 57],
       [39, 60, 95, 37],
       [18, 36, 20, 73],
       [56, 83, 60, 31],
       [11, 48, 94, 76]])

In [ ]:
np.sort(data,axis=0)

array([[11, 36, 20, 17],
       [16, 42, 23, 31],
       [18, 48, 31, 37],
       [35, 49, 45, 50],
       [39, 60, 48, 57],
       [41, 69, 50, 58],
       [46, 74, 60, 69],
       [56, 78, 94, 70],
       [78, 79, 95, 73],
       [89, 83, 96, 76]])

In [ ]:
np.sort(data,axis=1)

array([[31, 35, 50, 74],
       [42, 50, 70, 89],
       [17, 48, 49, 78],
       [16, 45, 69, 78],
       [46, 58, 79, 96],
       [23, 41, 57, 69],
       [37, 39, 60, 95],
       [18, 20, 36, 73],
       [31, 56, 60, 83],
       [11, 48, 76, 94]])

In [ ]:
np.sort(data[:,[1]],axis=0)

array([[36],
       [42],
       [48],
       [49],
       [60],
       [69],
       [74],
       [78],
       [79],
       [83]])

filtering

In [ ]:
x=np.array([1,2,3,4,5])
f=[True,False,True,False,True]
x[f]
#square brackets:condition to filter

array([1, 3, 5])